import Thumbnail01 from "@/public/images/news-thumbnail-01.jpeg";
import Thumbnail02 from "@/public/images/news-thumbnail-02.jpeg";
import Thumbnail03 from "@/public/images/news-thumbnail-03.jpeg";
import Thumbnail04 from "@/public/images/news-thumbnail-04.jpeg";
import Thumbnail05 from "@/public/images/news-thumbnail-05.jpeg";
import { NewsArticle } from "@/types/news-article";

export const salesNews: NewsArticle[] = [
  {
    id: "1",
    date: "SEP 20, 2025",
    subject: "UI Design",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail05,
  },
  {
    id: "2",
    date: "SEP 21, 2025",
    subject: "Employee Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail04,
  },
  {
    id: "3",
    date: "SEP 22, 2025",
    subject: "Health",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail03,
  },
  {
    id: "4",
    date: "SEP 23, 2025",
    subject: "UI Design",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail05,
  },
  {
    id: "5",
    date: "SEP 24, 2025",
    subject: "Employee Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail04,
  },
  {
    id: "6",
    date: "SEP 25, 2025",
    subject: "Health",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail03,
  },
  {
    id: "7",
    date: "SEP 26, 2025",
    subject: "UI Design",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail05,
  },
  {
    id: "8",
    date: "SEP 27, 2025",
    subject: "Employee Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail04,
  },
  {
    id: "9",
    date: "SEP 28, 2025",
    subject: "Health",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail03,
  },
  {
    id: "10",
    date: "SEP 29, 2025",
    subject: "UI Design",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail05,
  },
  {
    id: "11",
    date: "SEP 30, 2025",
    subject: "Employee Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail04,
  },
  {
    id: "12",
    date: "SEP 2, 2025",
    subject: "Health",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail03,
  },
  {
    id: "13",
    date: "SEP 20, 2025",
    subject: "UI Design",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail05,
  },
  {
    id: "14",
    date: "SEP 21, 2025",
    subject: "Employee Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail04,
  },
  {
    id: "15",
    date: "SEP 2, 2025",
    subject: "Health",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail03,
  },
];

export const companyNews: NewsArticle[] = [
  {
    id: "1",
    date: "SEP 20, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "2",
    date: "SEP 21, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
  {
    id: "3",
    date: "SEP 22, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "4",
    date: "SEP 23, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
  {
    id: "5",
    date: "SEP 24, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "6",
    date: "SEP 25, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
  {
    id: "7",
    date: "SEP 26, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "8",
    date: "SEP 27, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
  {
    id: "9",
    date: "SEP 28, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "10",
    date: "SEP 29, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
  {
    id: "11",
    date: "SEP 10, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "12",
    date: "SEP 11, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
  {
    id: "13",
    date: "SEP 10, 2025",
    subject: "Customer Experience",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail02,
  },
  {
    id: "14",
    date: "SEP 11, 2025",
    subject: "Artificial Intelligence",
    title: "New Site Launch Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    thumbnail: Thumbnail01,
  },
];
